-- Consolidated schema for RunSight
-- This file is auto-generated by concatenating the migration files.
-- To set up a new database, execute this entire script in the Supabase SQL Editor.

-- From migration: 20250609100000_fresh_start_simple_schema.sql
-- =================================================================
-- Drop existing complex tables if they exist
DROP TABLE IF EXISTS public.run_splits CASCADE;
DROP TABLE IF EXISTS public.enriched_runs CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.weather CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.user_tokens CASCADE; -- Removing as it is no longer needed

-- Drop existing functions if they exist
DROP FUNCTION IF EXISTS public.generate_strava_user_uuid(bigint);

-- Create runs table
CREATE TABLE public.runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  strava_id bigint UNIQUE NOT NULL,
  name text NOT NULL,
  distance real NOT NULL,
  moving_time integer NOT NULL,
  elapsed_time integer NOT NULL,
  start_date timestamptz NOT NULL,
  start_date_local timestamptz NOT NULL,
  start_latlng point,
  end_latlng point,
  average_speed real,
  max_speed real,
  average_heartrate real,
  max_heartrate real,
  total_elevation_gain real,
  weather_data jsonb,
  strava_data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX idx_runs_user_id ON public.runs(user_id);
CREATE INDEX idx_runs_strava_id ON public.runs(strava_id);
CREATE INDEX idx_runs_start_date ON public.runs(start_date DESC);

-- From migration: 20250609110000_add_proper_rls_security.sql
-- =================================================================
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own runs" ON public.runs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can only insert their own runs" ON public.runs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can only update their own runs" ON public.runs FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can only delete their own runs" ON public.runs FOR DELETE USING (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.runs TO authenticated;

-- From migration: 20250610200000_add_geocoding_columns.sql
-- =================================================================
ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS city TEXT NULL, ADD COLUMN IF NOT EXISTS state TEXT NULL, ADD COLUMN IF NOT EXISTS country TEXT NULL;

-- From migration: 20250717000000_create_goals_table.sql
-- =================================================================
CREATE TABLE IF NOT EXISTS goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('distance', 'time', 'frequency', 'pace')),
    title TEXT NOT NULL,
    description TEXT,
    target_value NUMERIC NOT NULL CHECK (target_value > 0),
    current_value NUMERIC DEFAULT 0,
    unit TEXT NOT NULL,
    target_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'failed')),
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
    category TEXT DEFAULT 'annual' CHECK (category IN ('annual', 'monthly', 'weekly', 'race_specific')),
    additional_details JSONB DEFAULT '{}'::jsonb
);

ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own goals" ON goals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own goals" ON goals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own goals" ON goals FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own goals" ON goals FOR DELETE USING (auth.uid() = user_id);
GRANT ALL ON goals TO authenticated;

-- From migration: 20250812000000_add_advanced_training_metrics.sql
-- =================================================================
ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS advanced_metrics JSONB;

CREATE TABLE IF NOT EXISTS public.user_training_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  resting_heart_rate integer,
  max_heart_rate integer,
  estimated_weight real,
  current_vo2_max real,
  current_ctl real,
  current_atl real,
  current_tsb real,
  optimal_temperature real,
  heat_tolerance_level text,
  heart_rate_zones jsonb,
  pace_zones jsonb,
  last_calculated timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.daily_training_load (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  date date NOT NULL,
  total_distance real DEFAULT 0,
  total_trimp real DEFAULT 0,
  total_moving_time integer DEFAULT 0,
  run_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, date)
);

ALTER TABLE public.user_training_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own training profile" ON public.user_training_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own training profile" ON public.user_training_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own training profile" ON public.user_training_profiles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own training profile" ON public.user_training_profiles FOR DELETE USING (auth.uid() = user_id);
GRANT ALL ON public.user_training_profiles TO authenticated;

ALTER TABLE public.daily_training_load ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own training load" ON public.daily_training_load FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own daily training load" ON public.daily_training_load FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own daily training load" ON public.daily_training_load FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own daily training load" ON public.daily_training_load FOR DELETE USING (auth.uid() = user_id);
GRANT ALL ON public.daily_training_load TO authenticated;