-- RunSight Base Schema & Security Model
-- Run this file in your Supabase SQL Editor to initialize the database.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Create timestamp trigger function
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 2. Create the runs table (activity data)
CREATE TABLE public.runs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strava_id bigint UNIQUE NOT NULL,
  name text NOT NULL,
  distance_meters real NOT NULL CHECK (distance_meters >= 0),
  moving_time_seconds integer NOT NULL CHECK (moving_time_seconds >= 0),
  elapsed_time_seconds integer CHECK (elapsed_time_seconds >= 0),
  start_date timestamptz NOT NULL,
  start_date_local timestamptz NOT NULL,
  start_latitude real,
  start_longitude real,
  end_latitude real,
  end_longitude real,
  average_speed_ms real,
  max_speed_ms real,
  average_heartrate_bpm integer,
  max_heartrate_bpm integer,
  total_elevation_gain_meters real,
  activity_type text NOT NULL DEFAULT 'Run',
  strava_data jsonb,
  weather_data jsonb,
  city text,
  state text,
  country text,
  advanced_metrics jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_runs_strava_id ON public.runs(strava_id);
CREATE INDEX idx_runs_start_date ON public.runs(start_date DESC);
CREATE INDEX idx_runs_advanced_metrics ON public.runs USING gin (advanced_metrics);

CREATE TRIGGER trigger_touch_runs_updated_at
  BEFORE UPDATE ON public.runs
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

-- 3. Create user tokens table (OAuth storage)
CREATE TABLE public.user_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strava_user_id bigint UNIQUE NOT NULL,
  strava_access_token text NOT NULL,
  strava_refresh_token text NOT NULL,
  strava_expires_at bigint NOT NULL,
  user_name text,
  user_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_tokens_strava_user_id ON public.user_tokens(strava_user_id);

CREATE TRIGGER trigger_touch_user_tokens_updated_at
  BEFORE UPDATE ON public.user_tokens
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

-- 4. Create user training profiles table
CREATE TABLE public.user_training_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL UNIQUE,
  age smallint CHECK (age IS NULL OR age BETWEEN 13 AND 100),
  "bodyWeight" smallint CHECK ("bodyWeight" IS NULL OR "bodyWeight" BETWEEN 30 AND 200),
  "fitnessLevel" text CHECK ("fitnessLevel" IS NULL OR "fitnessLevel" IN ('beginner', 'intermediate', 'advanced', 'elite')),
  "maxHeartRate" smallint CHECK ("maxHeartRate" IS NULL OR "maxHeartRate" BETWEEN 120 AND 250),
  "restingHeartRate" smallint CHECK ("restingHeartRate" IS NULL OR "restingHeartRate" BETWEEN 30 AND 120),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_training_profiles_user_id ON public.user_training_profiles(user_id);

CREATE TRIGGER trigger_touch_user_training_profiles_updated_at
  BEFORE UPDATE ON public.user_training_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

COMMENT ON TABLE public.runs IS 'Self-hosted run activity store used by Netlify functions.';
COMMENT ON TABLE public.user_tokens IS 'Single-owner Strava OAuth token store used only by Netlify functions.';
COMMENT ON TABLE public.user_training_profiles IS 'Optional runner profile data used by advanced analytics surfaces.';

-- 5. Security & Row Level Security (RLS) Configuration
-- RunSight Web uses Netlify functions with the Supabase service role for all private data access.
-- We intentionally lock direct browser/anon roles out of private tables.

ALTER TABLE public.runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_training_profiles DISABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.runs FROM anon, authenticated;
REVOKE ALL ON TABLE public.user_tokens FROM anon, authenticated;
REVOKE ALL ON TABLE public.user_training_profiles FROM anon, authenticated;

REVOKE ALL ON SEQUENCE public.runs_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.user_tokens_id_seq FROM anon, authenticated;

GRANT ALL ON TABLE public.runs TO service_role;
GRANT ALL ON TABLE public.user_tokens TO service_role;
GRANT ALL ON TABLE public.user_training_profiles TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.runs_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_tokens_id_seq TO service_role;
